### ISSUE TITLE
CLAMS compile error

### ISSUE THREAD

**Issue by pammirato** [jotaraul/HOMe-Toolkit#1]
when trying to compile I get the following error:

[ 12%] Built target Create_video
[ 25%] Built target Dataset_statistics
[ 37%] Built target Label_rawlog
[ 50%] Built target Label_scene
[ 62%] Built target Localize_sensors
[ 62%] Built target Undistort
Scanning dependencies of target Process_rawlog
[ 75%] Building CXX object CMakeFiles/Process_rawlog.dir/src/process_rawlog.o
/home/ammirato/Object-Labeling-Toolkit/src/process_rawlog.cpp:39:55: fatal error: clams/discrete_depth_distortion_model.h: No such file or directory
compilation terminated.
make[2]: **\* [CMakeFiles/Process_rawlog.dir/src/process_rawlog.o] Error 1
make[1]: **\* [CMakeFiles/Process_rawlog.dir/all] Error 2
make: **\* [all] Error 2

I can't find this file, discrete_depth_distortion_model.h

**Comment by jotaraul** [comment]
Hi pammirato,

Are you trying to use discrete distortion parameters from CLAMS? It sounds strange otherwise.

Anyway, I'll take a look. Thank you for the report!

**Comment by pammirato** [comment]
no i just cloned the repository, installed the PCL and MRPT, and tried to compile. I didn't change anything. I think it fails on line 39 on process_rawlog.cpp.

**Comment by jotaraul** [comment]
Yep, it was an erroneous initialization of a variable within the CMake file. Please clone it again, clear your CMake caché and try, it should work now!

If you don't want to clone again, just replace the line 78 in the CMakeLists.txt file:

set(OLT_USING_CLAMS_INTRINSIC_CALIBRATION "binary" CACHE BOOL
  "Check if an intrinsic calibration by CLAMS of the RGB-D sensors within the dataset is available.")

by

set(OLT_USING_CLAMS_INTRINSIC_CALIBRATION "FALSE" CACHE BOOL
  "Check if an intrinsic calibration by CLAMS of the RGB-D sensors within the dataset is available.")

**Comment by pammirato** [comment]
well that fixed that issue, but I now I get another. Do I need to install CLAMS?

ammirato@bvision4:~/Object-Labeling-Toolkit/build$ make
[ 12%] Built target Create_video
[ 25%] Built target Dataset_statistics
[ 37%] Built target Label_rawlog
[ 50%] Built target Label_scene
[ 62%] Built target Localize_sensors
Linking CXX executable Process_rawlog
/usr/bin/ld: cannot find -lUndistort
/usr/bin/ld: cannot find -lUndistort
collect2: error: ld returned 1 exit status
make[2]: **\* [Process_rawlog] Error 1
make[1]: **\* [CMakeFiles/Process_rawlog.dir/all] Error 2
make: **\* [all] Error 2

**Comment by jotaraul** [comment]
Nop, CLAMS is not a mandatory dependency. You can use it if you calibrate a sensor with CLAMS, or continue without it otherwise.

I've sent a new fix. As before, clone and try again, or just replace line 125 in the CMakeList.txt file:

TARGET_LINK_LIBRARIES(Process_rawlog ${PCL_LIBRARIES} ${MRPT_LIBS} Undistort)

by

if (OLT_USING_CLAMS_INTRINSIC_CALIBRATION)
    TARGET_LINK_LIBRARIES(Process_rawlog ${PCL_LIBRARIES} ${MRPT_LIBS} Undistort)
else
    TARGET_LINK_LIBRARIES(Process_rawlog ${PCL_LIBRARIES} ${MRPT_LIBS})
endif(OLT_USING_CLAMS_INTRINSIC_CALIBRATION)

**Comment by pammirato** [comment]
it worked!!    I just had to change line 128 in CMakeLists.txt also, replace:

else

by 

else ()

thank you for your quick reply and awesome help!!

**Comment by jotaraul** [comment]
Happy that it worked! Enjoy the toolkit and thank you for reporting the bug :).
