### ISSUE TITLE
Problem compiling

### ISSUE THREAD

**Issue by Gitanjali450** [jotaraul/HOMe-Toolkit#3]
Hello,

I installed the mrpt dependency as mentioned here: https://www.mrpt.org/MRPT_in_GNU/Linux_repositories 

But I'm getting the following error:

Could not find a package configuration file provided by "mrpt-slam" with
  any of the following names:

    mrpt-slamConfig.cmake
    mrpt-slam-config.cmake

Could you please let me know what I need to do?

**Comment by jotaraul** [comment]
Hi @Gitanjali450,

MRPT has made deep changes since the time that OLT was developed, so it doesn't work with recent versions of MRPT. You can try an older one, like the mrpt-1.5 brack in its repo: https://github.com/MRPT/mrpt/tree/mrpt-1.5

I hope that solves the problem.

Best regards.
